using UnityEngine;

public class MusicAreaManagerAndDetector : MonoBehaviour
{
    public MusicArea currentMusicArea;
    public MusicManager musicManager;

    void Awake()
    {
        musicManager = FindObjectOfType<MusicManager>(); //Only if we want just one MusicManager
    }

    void OnTriggerEnter(Collider other)
    {
        if(other.GetComponent<MusicArea>() != null)
        {
            currentMusicArea = other.GetComponent<MusicArea>();
            if (!currentMusicArea.isFaderOnly)
            {
                musicManager.PlayCrossFadeMusic(currentMusicArea.musicToPlay, currentMusicArea.musicFadeInDuration, currentMusicArea.musicFadeInVolume, currentMusicArea.currentmusicTime);
            }

            if(currentMusicArea.isFadeOutCurrentMusicArea)
            {
                musicManager.FadeOutCurrentAudioTrack(currentMusicArea.musicFadeInDuration, 0f);
            }

            if (currentMusicArea.isFadeOutAllMusicAreas)
            {
                musicManager.FadeOutCurrentAudioTrack(currentMusicArea.musicFadeInDuration, 0f);
            }
        
        }
    }

    void OnTriggerExit(Collider other)
    {
        if (currentMusicArea != null)
        {
            if(musicManager.currentAudioTrack == musicManager.audioTrack1)
            {
                currentMusicArea.currentmusicTime = musicManager.audioTrack1.time + currentMusicArea.musicFadeInDuration;
            }
            else
            {
                currentMusicArea.currentmusicTime = musicManager.audioTrack2.time + currentMusicArea.musicFadeInDuration;
            }
            if (currentMusicArea.isFadeWhenExitArea)
            {
                musicManager.FadeOutCurrentAudioTrack(currentMusicArea.musicFadeInDuration, 0f);
            }
        }   
    }
}
